name: Deploy to AWS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '25'

    - name: Inject PEM files into META-INF
      run: |
        mkdir -p src/main/resources/META-INF
        echo "${{ secrets.PRIVATE_KEY_PEM }}" > src/main/resources/META-INF/privateKey.pem
        echo "${{ secrets.PUBLIC_KEY_PEM }}" > src/main/resources/META-INF/publicKey.pem
        chmod 600 src/main/resources/META-INF/*.pem

    - name: Build WAR
      run: mvn clean package
    
    - name: Upload Project to EC2
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        passphrase: ${{ secrets.EC2_SSH_PASSPHRASE }}
        source: "."
        target: "~/szachuz"

    - name: Cleanup PEM files
      if: always()
      run: |
        rm -f src/main/resources/META-INF/privateKey.pem
        rm -f src/main/resources/META-INF/publicKey.pem

    - name: Build & Run Containers on EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        passphrase: ${{ secrets.EC2_SSH_PASSPHRASE }}
        script: |
          cd ~/szachuz
          docker-compose build
          docker-compose down || true
          docker-compose up -d
